[package]
name = "html2text"
version = "0.1.0"
authors = ["Chris Emerson <github@mail.nosreme.org>"]

[dependencies]
html5ever = "*"
html5ever-atoms = "*"
string_cache = "0.2.0"
unicode-width = "*"
backtrace = "*"

[features]
html_trace = []

[[example]]
name = "html2term"
path = "examples/html2term.rs"

[dev-dependencies]
termion = "1.0"
argparse = "*"
