[package]
name = "html2text"
version = "0.1.2"
authors = ["Chris Emerson <github@mail.nosreme.org>"]
description = "Render HTML as plain text."
homepage = "https://github.com/jugglerchris/rust-html2text/"
repository = "https://github.com/jugglerchris/rust-html2text/"
readme = "README.md"

keywords = ["html", "text"]
license = "MIT"

[dependencies]
clippy = { version = "0.0.104", optional=true }
html5ever = "0.9"
html5ever-atoms = "0.1"
string_cache = "0.2.0"
unicode-width = "0.1"
backtrace = "0.2"

[features]
html_trace = []
default = []

[[example]]
name = "html2term"
path = "examples/html2term.rs"

[[example]]
name = "html2text"
path = "examples/html2text.rs"

[dev-dependencies]
termion = "1.0"
argparse = "0.2"
