name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test-action:
    name: Check semver compatibility
    runs-on: ubuntu-latest
    steps:
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v1
        with:
          version-tag-prefix: ''
